#so maybe this is a bit of an after-the-basic version, a kind of supplemental expansion.
#or an alternative approach or something.
#maybe the main page will attempt, on load, to retrieve supplemental details.json
# if they have happend to be generated by this docker image.
FROM networkstatic/nmap

ARG TARGETHOST=falchion.int.bry.com

RUN apk add nmap-scripts

RUN apk update
RUN apk add python3

#CMD which python3
#CMD nmap --script http-title $TARGETHOST -p 80-30000
#CMD nmap -sV $TARGETHOST

CMD echo $TARGETHOST

#Scan for open ssh (tcp/22) ports on a range of IPs
#docker run -it --rm networkstatic/nmap -sT 192.168.1.1-100 -p 22
#docker run -it --rm nmapigate -sT $HOSTNAME -p 5080
#docker run -it --rm nmapigate -sV $HOSTNAME -p 5080
#docker run -it --rm nmapigate -sV $HOSTNAME -p 5080 -oX - | xmllint --xpath 'string(//nmaprun/host/ports/port/service/@name)' -

# export TGTPORT=8087 ; ( docker run -it --rm nmapigate -sV $HOSTNAME -p $TGTPORT -oX - | xmllint --xpath 'string(//nmaprun/host/ports/port/service[@conf > 7]/@name)' - )



